spring.application.name=spring01

# 單一庫
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/brad?useSSL=false&serverTimezone=Asia/Taipei&characterEncoding=UTF-8
spring.datasource.username=root
spring.datasource.password=root

# 以下自訂
company.name=Brad Big Company
company.tel=04-12345678
name=Brad